image: node:latest

stages:
    - build

build:
    stage: build
    cache:
        paths:
            - node_modules/
    script:
        - npm install --quiet
        - npm run build --configuration=production

