image: node:latest

stages:
    - build
    - deploy

build:
    stage: build
    cache:
        paths:
            - node_modules/
    script:
        - npm install --quiet
        - npm run build-prod

deploy:
    stage: deploy
    